FROM node:18-alpine AS builder

# Create app directory
WORKDIR /app

# Install pnpm globaly
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml* ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy all files
COPY . .

# Set environment variables
ENV NODE_ENV=production

# Build application
RUN pnpm build

# Production image, copy all the files and run next
FROM node:18-alpine AS runner

WORKDIR /app

# Install pnpm globaly
RUN npm install -g pnpm

# Set environment variables
ENV NODE_ENV=production

# Copy built app
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["pnpm", "start"] 