version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    restart: always

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    restart: always

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always

  # Python AI Service
  python-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile.prod
    volumes:
      - ./ai-service:/app
    depends_on:
      - qdrant
      - redis
    restart: always

  # Qdrant Vector Store
  qdrant:
    image: qdrant/qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # Redis Cache
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always

volumes:
  qdrant_data:
  mysql_data:
  redis_data: 