services:
  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
      - PYTHON_SERVICE_HOST=python-service

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  # Python AI Service
  python-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ai-service:/app
    depends_on:
      - qdrant
      - redis

  # Qdrant Vector Store
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: banhang_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banhang
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - banhang_network

  # Redis Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: banhang_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - banhang_network

volumes:
  qdrant_data:
  mysql_data:
  redis_data:

networks:
  banhang_network:
    driver: bridge 