version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    restart: always

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=testing
      - APP_DEBUG=true
      - APP_URL=https://test.banhang.ai
    restart: always
    command: php artisan serve --host=0.0.0.0 --port=8001

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: always
    command: sh -c "npm run build && npm start"

  # Python AI Service
  python-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ai-service:/app
      - /app/venv
    depends_on:
      - qdrant
      - redis
    restart: always

  # Qdrant Vector Store
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_test_data:/qdrant/storage
    restart: always

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=banhang_test
    volumes:
      - mysql_test_data:/var/lib/mysql
    restart: always

  # Redis Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    restart: always

  # PhpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql

volumes:
  qdrant_test_data:
  mysql_test_data:
  redis_test_data: 